# Collectors
-include collectors/exchange-coinmarketcap-history-data/Makefile

# Analyzers
-include analyzers/sigma_analyzer/Makefile

# Solver

# Adapters
-include adapters/telegram-notifier/Makefile