services:
  telegram-notifier:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-telegram-notifier
    restart: unless-stopped
    env_file:
      - ../../.env
      - .env
    networks:
      - bot-network
    #depends_on:
    #  - kafka

networks:
  bot-network:
    name: ${COMPOSE_PROJECT_NAME}-network
    external: true
