services:
  telegram-notifier:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-telegram-notifier
    restart: unless-stopped
    environment:
      KAFKA_URL: kafka:9092
      KAFKA_TOPIC: notifications
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHANNEL_ID: ${TELEGRAM_DEFAULT_CHANNEL_ID}
      LOGGED_LEVELS: ${TELEGRAM_LOGGED_LIST}
    networks:
      - bot-network
    depends_on:
      - kafka

networks:
  bot-network:
    external: true
